# version 4.x
debug: True

paths:
  tournoi: data/tournoi.json
  participants: data/participants.json
  stream: data/stream.json
  stagelist: data/stagelist.yml

discord:
  secret:
  guild:
  channels:
    blabla:
    annonce:
    check_in:
    inscriptions:
    scores:
    stream:
    queue:
    tournoi:
    deroulement:
    faq:
    resultats:
  categories:
    tournoi:
    arenes:
  roles:
    challenger:
    to:
  emojis:
    logo:

challonge:
  user:
  api_key:
