version: '3'

services:
  atos:
    build: .
    container_name: atos
    restart: unless-stopped
    environment:
      - TZ = Europe/Berlin
    volumes:
      - ./config:/bot/config
      - ./data:/bot/data
