# version 5.x
system:
  debug: True
  auto_mode: False
  language: fr_FR

paths:
  tournoi: data/tournoi.json
  participants: data/participants.json
  waiting_list: data/waiting_list.json
  stream: data/stream.json
  stagelist: config/stagelist.yml
  auto_mode: config/auto_mode.yml

discord:
  secret:
  guild:
  prefix:
  channels:
    blabla:
    annonce:
    check_in:
    inscriptions:
    scores:
    stream:
    queue:
    tournoi:
    deroulement:
    faq:
    resultats:
    roles:
  categories:
    tournoi:
    arenes:
  roles:
    challenger:
    to:
  emojis:
    logo:

challonge:
  user:
  api_key:
