# version 5.x
system:
  debug: True
  auto_mode: False
  bulk_mode: False
  use_guild_name: False
  greet_new_members: False
  manage_game_roles: False
  language: fr_FR

paths:
  tournoi: data/tournoi.json
  participants: data/participants.json
  waiting_list: data/waiting_list.json
  stream: data/stream.json
  ranking: data/ranking.csv
  stagelist: config/stagelist.yml
  auto_mode: config/auto_mode.yml

discord:
  secret:
  guild:
  prefix:
  channels:
    blabla:
    annonce:
    check_in:
    inscriptions:
    scores:
    stream:
    queue:
    tournoi:
    deroulement:
    faq:
    resultats:
    roles:
    to:
  categories:
    tournoi:
    winner:
    looser:
  roles:
    challenger:
    to:
    streamer:
  emojis:
    logo:

challonge:
  user:
  api_key:
