Game 1:
  ruleset:
  role:
#  role_1v1:
  icon:
#  icon_1v1:
#  ranking:
#    league_name:
#    league_id:
  starters:
    - foo
#  counterpicks:
#    - bar

#Game 2:
#  ruleset:
#  role:
#  role_1v1:
#  icon:
#  icon_1v1:
#  ranking:
#    league_name:
#    league_id:
#  starters:
#    - foo
#  counterpicks:
#    - bar
