auto_mode: False
bulk_mode: False
check_channel_presence: 15
check_in_closing: 15 # MINUTES before tournament
check_in_opening: 60 # MINUTES before tournament
full_bo3: False
full_bo5: False # Has priority over full_bo3
inscriptions_closing: 10 # MINUTES before tournament
inscriptions_opening: 30 # HOURS before tournament, useful for auto-mode ONLY
reaction_mode: True
restrict_to_role: False
start_bo5: 0 # When to start BO5 (0 = top 8, +1 = top 6, -1 = top 12, etc.)
use_guild_name: True